name: DAST

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: php-actions/composer@v6 # or alternative dependency management

      - name: Build
        run: |
          docker-compose up -d
          # You might need to add more commands like testing, etc.
          
      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://0.0.0.0:8000'
